name: CI Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  tests-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"

      - name: Run CI tests (PowerShell)
        run: .\\scripts\\run_ci_tests.ps1
        shell: pwsh
        env:
          TEST_ALLOW_LOGIN: "true"
          APP_ENV: "testing"
